name: Docs to Vector

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Payload
        id: payload
        run: |
          payload=$(jq -n \
            --arg current_commit_id "${{ github.sha }}" \
            --arg branch_name "${{ github.ref_name }}" \
            --arg repo_name "${{ github.event.repository.name }}" \
            '{
              current_commit_id: $current_commit_id,
              branch_name: $branch_name,
              repo_name: $repo_name,
            }')
          echo "$payload" > /tmp/payload.json
          
      - name: Call Webhook (Preview)
        run: |
          payload=$(cat /tmp/payload.json)
          sig=$(printf '%s' "$payload" | \
              openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" -binary | xxd -p -c 256)
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Hub-Signature-256: sha256=$sig" \
            -d "$payload" \
            ${{ secrets.WEBHOOK_URL }}